[term]
color = 'always'

[profile.bench]
incremental = true
codegen-units = 32

[profile.release]
incremental = true
codegen-units = 32

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
